name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: '3.9'
    strategy:
      matrix:
        python: ['3.10','3.9']
    steps:
    - uses: actions/checkout@master
    - name: Python ${{ matrix.python }} version
      uses: actions/setup-python@v4
      with:
          python-version: ${{ matrix.python }}
          architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd src
        pip install -r requirements/dev.txt --use-deprecated=legacy-resolver
    - name: Test with pytest
      run: |
        cd src
        cp .env_sample .env
        python3 -m pytest